global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: app-python
    static_configs:
      - targets: ['app_python:8000']

  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]