name: JavaScript CI

on:
  push:
    paths:
      - 'app_javascript/**'
      - '.github/workflows/javascript_ci.yaml'

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Node.js dependencies
      run: npm install
      working-directory: app_javascript

  docker:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Node.js dependencies
      run: npm install
      working-directory: app_javascript

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/app_javascript:latest app_javascript/.
        docker push ${{ secrets.DOCKER_USERNAME }}/app_javascript:latest
