name: Python CI

on:
  push:
    paths:
      - 'app_python/**'
      - '.github/workflows/python_ci.yaml'

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app_python/requirements.txt

    - name: Lint code
      run: |
        flake8

  testing:

    runs-on: ubuntu-22.04

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app_python/requirements.txt

    - name: Run Tests
      run: |
        python -m unittest app_python/test_app.py

    - name: Download Snyk
      run: |
        curl -LO https://github.com/snyk/cli/releases/download/v1.1278.0/snyk-linux
        chmod +x snyk-linux
      working-directory: app_python

    - name: Run Snyk
      run: ./snyk-linux test --severity-threshold=high
      working-directory: app_python
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  docker:

    runs-on: ubuntu-22.04

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app_python/requirements.txt
        
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/app_python:latest app_python/.
        docker push ${{ secrets.DOCKER_USERNAME }}/app_python:latest